# Generated by Django 3.2.2 on 2021-05-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('name_area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreasTree',
            fields=[
                ('id_subarea', models.AutoField(primary_key=True, serialize=False)),
                ('name_subarea', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Areas_tree',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('name_data', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Data_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id_exp', models.IntegerField()),
                ('id_value', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Experiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentClass',
            fields=[
                ('id_field', models.AutoField(db_column='ID*', primary_key=True, serialize=False)),
                ('main_pict', models.CharField(blank=True, db_column='Main_pict', max_length=100, null=True)),
                ('geom_pict', models.CharField(blank=True, db_column='Geom_pict', max_length=100, null=True)),
                ('reg_pict', models.CharField(blank=True, db_column='Reg_pict', max_length=100, null=True)),
                ('tepl_pict', models.CharField(blank=True, db_column='Tepl_pict', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Experiment_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('user', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Log_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametrs',
            fields=[
                ('id_param', models.AutoField(primary_key=True, serialize=False)),
                ('name_param', models.CharField(max_length=100)),
                ('short_name_param', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_param', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Parametrs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PcConfiguration',
            fields=[
                ('id_pc', models.AutoField(db_column='id_PC', primary_key=True, serialize=False)),
                ('proc_name', models.CharField(max_length=100)),
                ('proc_freq', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('proc_arch', models.CharField(max_length=100)),
                ('num_cores', models.IntegerField()),
                ('amount_ram', models.DecimalField(db_column='amount_RAM', decimal_places=65535, max_digits=65535)),
                ('type_ram', models.CharField(db_column='type_RAM', max_length=1)),
                ('sys_cap', models.IntegerField()),
                ('gpu', models.CharField(db_column='GPU', max_length=1)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'PC Configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhPTPE',
            fields=[
                ('id_ph_p_t_p_e_field', models.AutoField(db_column='id_Ph.p._T.p.e.', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Ph.p._T.p.e.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalProcess',
            fields=[
                ('id_ph_p_field', models.AutoField(db_column='id_Ph.p.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Physical_process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareConfiguration',
            fields=[
                ('id_soft', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grid_gen', models.CharField(max_length=100)),
                ('calc_module', models.CharField(max_length=100)),
                ('type_license', models.CharField(max_length=100)),
                ('license_term', models.CharField(max_length=100)),
                ('workplaces', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Software configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfParametrs',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Type_of_parametrs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfPowerEquipment',
            fields=[
                ('id_t_p_e_field', models.AutoField(db_column='id_T.p.e.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Type_of_power_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnicExp',
            fields=[
                ('id_exp', models.IntegerField()),
                ('exp', models.AutoField(db_column='EXP', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Unic_EXP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('login', models.CharField(db_column='Login', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('level', models.TextField(db_column='Level')),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fca',
            fields=[
                ('exp', models.OneToOneField(db_column='EXP', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.unicexp')),
                ('grid_time', models.CharField(max_length=100)),
                ('calc_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FCA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametrsValues',
            fields=[
                ('id_value', models.OneToOneField(db_column='id_value', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.experiment')),
                ('value_number', models.DecimalField(blank=True, decimal_places=7, max_digits=14, null=True)),
                ('value_range', models.TextField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=100, null=True)),
                ('value_image', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Parametrs_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StringValues',
            fields=[
                ('id_param', models.OneToOneField(db_column='id_param', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.parametrs')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'String_values',
                'managed': False,
            },
        ),
    ]
