# Generated by Django 3.2.2 on 2021-06-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stringvalues',
            options={'managed': False, 'ordering': ['id_param']},
        ),
    ]
