# Generated by Django 3.2.2 on 2021-06-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stringvalues_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stringvalues',
            options={'managed': False},
        ),
    ]
